hc/urls.py
from __future__ import annotations

from django.contrib import admin
from django.urls import include, path

from hc.accounts import views as accounts_views

urlpatterns = [
    path("admin/login/", accounts_views.login),
    path("admin/", admin.site.urls),
    path("accounts/", include("hc.accounts.urls")),
    path("projects/add/", accounts_views.add_project, name="hc-add-project"),
    path(
        "projects/<uuid:code>/settings/",
        accounts_views.project,
        name="hc-project-settings",
    ),
    path(
        "projects/<uuid:code>/remove/",
        accounts_views.remove_project,
        name="hc-remove-project",
    ),
    path("", include("hc.api.urls")),
    path("", include("hc.front.urls")),
    path("", include("hc.payments.urls")),
]

hc/api/models.py
from __future__ import annotations

import hashlib
import json
import socket
import uuid
from dataclasses import dataclass
from datetime import datetime
from datetime import timedelta as td
from datetime import timezone
from typing import Any, TypedDict
from urllib.parse import urlencode
from zoneinfo import ZoneInfo

from cronsim import CronSim
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.core.mail import mail_admins
from django.core.signing import TimestampSigner
from django.db import models, transaction
from django.db.models import F, QuerySet
from django.http import HttpRequest
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.timezone import now
from oncalendar import OnCalendar
from pydantic import BaseModel, Field

from hc.accounts.models import Project
from hc.api import transports
from hc.lib import emails
from hc.lib.date import month_boundaries, seconds_in_month
from hc.lib.s3 import get_object, put_object, remove_objects

STATUSES = (("up", "Up"), ("down", "Down"), ("new", "New"), ("paused", "Paused"))
DEFAULT_TIMEOUT = td(days=1)
DEFAULT_GRACE = td(hours=1)
NEVER = datetime(3000, 1, 1, tzinfo=timezone.utc)
CHECK_KINDS = (("simple", "Simple"), ("cron", "Cron"), ("oncalendar", "OnCalendar"))
# max time between start and ping where we will consider both events related:
MAX_DURATION = td(hours=72)

TRANSPORTS: dict[str, tuple[str, type[transports.Transport]]] = {
    "apprise": ("Apprise", transports.Apprise),
    "call": ("Phone Call", transports.Call),
    "discord": ("Discord", transports.Discord),
    "email": ("Email", transports.Email),
    "gotify": ("Gotify", transports.Gotify),
    "group": ("Group", transports.Group),
    "linenotify": ("LINE Notify", transports.LineNotify),
    "matrix": ("Matrix", transports.Matrix),
    "mattermost": ("Mattermost", transports.Mattermost),
    "msteams": ("MS Teams Connector (stops working Dec 2024)", transports.MsTeams),
    "msteamsw": ("Microsoft Teams", transports.MsTeamsWorkflow),
    "ntfy": ("ntfy", transports.Ntfy),
    "opsgenie": ("Opsgenie", transports.Opsgenie),
    "pagertree": ("PagerTree", transports.PagerTree),
    "pd": ("PagerDuty", transports.PagerDuty),
    "po": ("Pushover", transports.Pushover),
    "pushbullet": ("Pushbullet", transports.Pushbullet),
    "rocketchat": ("Rocket.Chat", transports.RocketChat),
    "shell": ("Shell Command", transports.Shell),
    "signal": ("Signal", transports.Signal),
    "slack": ("Slack", transports.Slack),
    "sms": ("SMS", transports.Sms),
    "spike": ("Spike", transports.Spike),
    "telegram": ("Telegram", transports.Telegram),
    "trello": ("Trello", transports.Trello),
    "victorops": ("Splunk On-Call", transports.VictorOps),
    "webhook": ("Webhook", transports.Webhook),
    "whatsapp": ("WhatsApp", transports.WhatsApp),
    "zulip": ("Zulip", transports.Zulip),
}


CHANNEL_KINDS = [(kind, label_cls[0]) for kind, label_cls in TRANSPORTS.items()]

PO_PRIORITIES = {
    -3: "disabled",
    -2: "lowest",
    -1: "low",
    0: "normal",
    1: "high",
    2: "emergency",
}

NTFY_PRIORITIES = {
    5: "max",
    4: "high",
    3: "default",
    2: "low",
    1: "min",
    0: "disabled",
}


def isostring(dt: datetime | None) -> str | None:
    """Convert the datetime to ISO 8601 format with no microseconds."""
    return dt.replace(microsecond=0).isoformat() if dt else None


class CheckDict(TypedDict, total=False):
    uuid: str | None
    name: str
    slug: str
    tags: str
    desc: str
    grace: int
    n_pings: int
    status: str
    started: bool
    last_ping: str | None
    next_ping: str | None
    manual_resume: bool
    methods: str
    subject: str
    subject_fail: str
    start_kw: str
    success_kw: str
    failure_kw: str
    filter_subject: bool
    filter_body: bool
    last_duration: int
    unique_key: str
    ping_url: str
    update_url: str
    pause_url: str
    resume_url: str
    channels: str
    timeout: int
    schedule: str
    tz: str


@dataclass
class DowntimeRecord:
    boundary: datetime  # The start of this time interval (timezone-aware)
    tz: str  # For calculating total seconds in a month
    no_data: bool  # True if the check did not yet exist in this time interval
    duration: td  # Total downtime in this time interval
    count: int  # The number of downtime events in this time interval

    def monthly_uptime(self) -> float:
        # NB: this method assumes monthly boundaries.
        # It will yield incorrect results for weekly boundaries
        max_seconds = seconds_in_month(self.boundary.date(), self.tz)
        up_seconds = max_seconds - self.duration.total_seconds()
        return up_seconds / max_seconds


class DowntimeRecorder(object):
    def __init__(self, boundaries: list[datetime], tz: str, created: datetime) -> None:
        """
        `boundaries` is a list of timezone-aware datetimes of the starts of time
        intervals (months or weeks), and should be pre-sorted in descending order.
        """
        self.records = []
        prev_boundary = None
        for b in boundaries:
            # If the check was created *after* the start of the previous time
            # interval then the check did not yet exist during this time interval:
            no_data = prev_boundary is not None and created > prev_boundary
            self.records.append(DowntimeRecord(b, tz, no_data, td(), 0))
            prev_boundary = b

    def add(self, when: datetime, duration: td) -> None:
        for record in self.records:
            if when >= record.boundary:
                record.duration += duration
                record.count += 1
                return


class Check(models.Model):
    name = models.CharField(max_length=100, blank=True)
    slug = models.CharField(max_length=100, blank=True)
    tags = models.CharField(max_length=500, blank=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    desc = models.TextField(blank=True)
    project = models.ForeignKey(Project, models.CASCADE)
    created = models.DateTimeField(default=now)
    kind = models.CharField(max_length=10, default="simple", choices=CHECK_KINDS)
    timeout = models.DurationField(default=DEFAULT_TIMEOUT)
    grace = models.DurationField(default=DEFAULT_GRACE)
    schedule = models.CharField(max_length=100, default="* * * * *")
    tz = models.CharField(max_length=36, default="UTC")
    filter_subject = models.BooleanField(default=False)
    filter_body = models.BooleanField(default=False)
    start_kw = models.CharField(max_length=200, blank=True)
    success_kw = models.CharField(max_length=200, blank=True)
    failure_kw = models.CharField(max_length=200, blank=True)
    methods = models.CharField(max_length=30, blank=True)
    manual_resume = models.BooleanField(default=False)
    badge_key = models.UUIDField(null=True, unique=True)

    n_pings = models.IntegerField(default=0)
    last_ping = models.DateTimeField(null=True, blank=True)
    last_start = models.DateTimeField(null=True, blank=True)
    last_start_rid = models.UUIDField(null=True)
    last_duration = models.DurationField(null=True, blank=True)
    has_confirmation_link = models.BooleanField(default=False)
    alert_after = models.DateTimeField(null=True, blank=True, editable=False)
    status = models.CharField(max_length=6, choices=STATUSES, default="new")

    class Meta:
        indexes = [
            # Index for the alert_after field. Exclude rows with status=down.
            # Used in the sendalerts management command.
            models.Index(
                fields=["alert_after"],
                name="api_check_aa_not_down",
                condition=~models.Q(status="down"),
            ),
            models.Index(fields=["project_id", "slug"], name="api_check_project_slug"),
        ]

    def __str__(self) -> str:
        return "%s (%d)" % (self.name or self.code, self.id)

    def name_then_code(self) -> str:
        if self.name:
            return self.name

        return str(self.code)

    def url(self) -> str | None:
        """Return check's ping url in user's preferred style.

        Note: this method reads self.project. If project is not loaded already,
        this causes a SQL query.

        """

        if self.project_id and self.project.show_slugs:
            if not self.slug:
                return None

            # If ping_key is not set, use dummy placeholder
            key = self.project.ping_key or "{ping_key}"
            return settings.PING_ENDPOINT + key + "/" + self.slug

        return settings.PING_ENDPOINT + str(self.code)

    def details_url(self, full: bool = True) -> str:
        result = reverse("hc-details", args=[self.code])
        return settings.SITE_ROOT + result if full else result

    def get_absolute_url(self) -> str:
        return self.details_url(full=False)

    def cloaked_url(self) -> str:
        return settings.SITE_ROOT + reverse("hc-uncloak", args=[self.unique_key])

    def email(self) -> str:
        return "%s@%s" % (self.code, settings.PING_EMAIL_DOMAIN)

    def clamped_last_duration(self) -> td | None:
        if self.last_duration and self.last_duration < MAX_DURATION:
            return self.last_duration
        return None

    def get_grace_start(self, *, with_started: bool = True) -> datetime | None:
        """Return the datetime when the grace period starts.

        If the check is currently new, paused or down, return None.
        """
        # NEVER is a constant sentinel value (year 3000).
        # Using None instead would make the min() logic clunky.
        result = NEVER

        if self.kind == "simple" and self.status == "up":
            assert self.last_ping is not None
            result = self.last_ping + self.timeout
        elif self.kind == "cron" and self.status == "up":

templates/integrations/add_discord.html
{% extends "base_project.html" %}
{% load humanize static hc_extras %}

{% block title %}Discord Integration for {{ site_name }}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>Discord</h1>

    <div class="jumbotron">
        <p>
            With this integration, {{ site_name }} will send
            a notification to a <a href="http://discord.com/">Discord</a>
            channel when a check
            goes <strong>up</strong> or <strong>down</strong>.
        </p>

        <form method="post" class="text-center">
            {% csrf_token %}
            <a href="{{ authorize_url }}" class="btn btn-lg btn-default">
                <img class="ai-icon" src="{% static 'img/integrations/discord.png' %}" alt="Discord" />
                Connect Discord
            </a>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/integrations/add_pagertree.html
{% extends "base_project.html" %}
{% load humanize static hc_extras %}

{% block title %}PagerTree Integration for {{ site_name }}{% endblock %}


{% block content %}
<div class="row">
  <div class="col-sm-12">
      <h1>PagerTree</h1>

      <p>If your team uses <a href="https://pagertree.com">PagerTree</a>,
      you can set up {{ site_name }} to create a PagerTree alert when
      a check goes down, and resolve it when a check goes back up.</p>

      <h2>Setup Guide</h2>

      <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
                Log into your PagerTree account, navigate to the <a href="https://app.pagertree.com/integrations?direction=asc&limit=10&sort=tiny_id" target="_blank">Integrations page</a>.
                Then click the <strong>New Integration</strong> button and
                select the <strong>Healthchecks</strong> logo.
            </p>
        </div>
        <div class="col-sm-6">
            <div class="marker-wrap">
                <span style="left: 89%; top: 35%;" class="marker"></span>
                <img
                    class="ai-guide-screenshot"
                    alt="Click create integration button"
                    src="{% static 'img/integrations/setup_pagertree_1.png' %}" />
            </div>
        </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no"></span>
              <p>
                  In the New Integration Form, fill out the details with appropriate values. Then click the <strong>Create</strong> button.
              </p>
          </div>
          <div class="col-sm-6">
              <img
                  class="ai-guide-screenshot"
                  alt="Create Healthchecks.io integration with details"
                  src="{% static 'img/integrations/setup_pagertree_2.png' %}">
          </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no"></span>
              <p>
                Copy the <strong>Endpoint URL</strong> and paste it
                in the form below.
                Save the integration, and you are done!
              </p>
          </div>
          <div class="col-sm-6">
            <div class="marker-wrap">
                <span style="left: 48.5%; top: 87%;" class="marker"></span>

                  <img
                      class="ai-guide-screenshot"
                      alt="Copy the Webhook URL"
                      src="{% static 'img/integrations/setup_pagertree_3.png' %}">
            </div>
          </div>
      </div>

      <h2>Integration Settings</h2>

      <form method="post" class="form-horizontal">
          {% csrf_token %}
          <div class="form-group {{ form.value.css_classes }}">
              <label for="post-url" class="col-sm-2 control-label">Endpoint</label>
              <div class="col-sm-10">
                  <input
                      id="post-url"
                      type="text"
                      class="form-control"
                      name="value"
                      placeholder="https://"
                      value="{{ form.value.value|default:"" }}">

                  {% if form.value.errors %}
                  <div class="help-block">
                      {{ form.value.errors|join:"" }}
                  </div>
                  {% endif %}
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">Save Integration</button>
              </div>
          </div>
      </form>
  </div>
</div>
{% endblock %}

templates/integrations/add_slack_btn.html
{% extends "base_project.html" %}
{% load humanize static hc_extras %}

{% block title %}{% site_name %} Integration for Slack{% endblock %}

{% block description %}
    <meta name="description" content="Use {% site_name %} with Slack: configure {% site_name %} to post status updates directly to a Slack channel.">
{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-12">

    <div class="jumbotron">
        {% if request.user.is_authenticated %}
        <p>If your team uses <a href="https://slack.com/">Slack</a>, you can set
        up {% site_name %} to post status updates directly to an appropriate
        Slack channel.</p>

        {% if authorize_url %}
        <div class="text-center">
        <a href="{{ authorize_url }}">
            <img
                alt="Add to Slack"
                src="{% static 'img/integrations/add_to_slack.png' %}"
                srcset="{% static 'img/integrations/add_to_slack.png' %} 1x, {% static 'img/integrations/add_to_slack@2x.png' %} 2x" />
        </a>
        </div>
        {% endif %}

        {% else %}
        <p>
        {% site_name %} is a <strong>free</strong> and
        <a href="https://github.com/healthchecks/healthchecks">open source</a>
        service for monitoring your cron jobs, background processes and
        scheduled tasks. To set up a {% site_name %} integration for Slack, please
        log into {% site_name %}:</p>

        <div class="text-center">
            <a href="{% url 'hc-login' %}"
               class="btn btn-primary btn-lg">Log In</a>
        </div>
        {% endif %}
    </div>

    <h2>Setup Guide</h2>

    {% if not authorize_url %}
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
                {% if request.user.is_authenticated %}
                Go
                {% else %}
                After logging in, go
                {% endif %}

                to the <strong>Integrations</strong> page,
                and click on <strong>Add Integration</strong> next to the
                Slack icon.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_0.png' %}">
        </div>
    </div>
    {% endif %}

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
                Click on the "Add to Slack" button, and you should
                be on a page that says "{% site_name %} would like access to
                your Slack team". Select the team you want to add the
                {% site_name %} integration app to.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_1.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
                You should now be on a page that says "{% site_name %} would
                like access to <i>TEAM NAME</i>". Select the channel you want to
                post {% site_name %} notifications to.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_2.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
                That is all! You will now be redirected back to
                "Integrations" page on {% site_name %} and see
                the new integration!
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_3.png' %}">
        </div>
    </div>

</div>
</div>
{% endblock %}

templates/integrations/add_spike.html
{% extends "base_project.html" %}
{% load humanize static hc_extras %}

{% block title %}Spike.sh Integration for {{ site_name }}{% endblock %}


{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Spike.sh</h1>

        <p>If you are using <a href="https://spike.sh">Spike.sh</a>,
            you can set up {{ site_name }} to create a Spike.sh incident when a check
            goes down, and resolve it when a check goes back up.</p>

        <h2>Setup Guide</h2>

        <div class="row ai-step">
            <div class="col-sm-6">
                <span class="step-no"></span>
                <p>
                    Log into your Spike.sh account and go to
                    <strong>Integrations › New integration</strong>.
                    Select "Healthchecks" and click "Next".
                </p>
            </div>
            <div class="col-sm-6">
                <img class="ai-guide-screenshot" alt="Click create integration button"
                    src="{% static 'img/integrations/setup_spike_1.png' %}" />
            </div>
        </div>

        <div class="row ai-step">
            <div class="col-sm-6">
                <span class="step-no"></span>
                <p>
                    Give the integration a descriptive <strong>name</strong> and select
                    the Spike.sh <strong>service</strong> to add it to.
                </p>
                <p>
                    In the following step, create or select an existing
                    <strong>escalation policy</strong> to associate with the
                    integration.
                </p>
            </div>
            <div class="col-sm-6">
                <img class="ai-guide-screenshot" alt="Click create integration button"
                    src="{% static 'img/integrations/setup_spike_2.png' %}" />
            </div>
        </div>

        <div class="row ai-step">
            <div class="col-sm-6">
                <span class="step-no"></span>
                <p>
                    After you have created the integration, click on
                    <strong>Copy Webhook</strong>.

                </p>
            </div>
            <div class="col-sm-6">
                <img class="ai-guide-screenshot" alt="Create Healthchecks.io integration with details"
                    src="{% static 'img/integrations/setup_spike_3.png' %}">
            </div>
        </div>

        <div class="row ai-step">
            <div class="col-sm-6">
                <span class="step-no"></span>
                <p>
                    Copy the shown webhook URL and paste it in the form below.
                    Save the integration, and you are done!
                </p>
            </div>
            <div class="col-sm-6">
                <img class="ai-guide-screenshot" alt="Copy the Webhook URL"
                    src="{% static 'img/integrations/setup_spike_4.png' %}">
            </div>
        </div>

        <h2>Integration Settings</h2>

        <form method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group {{ form.value.css_classes }}">
                <label for="post-url" class="col-sm-2 control-label">Webhook URL</label>
                <div class="col-sm-10">
                    <input id="post-url" type="text" class="form-control" name="value" placeholder="https://"
                        value="{{ form.value.value|default:"" }}">

                    {% if form.value.errors %}
                    <div class="help-block">
                        {{ form.value.errors|join:"" }}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Save Integration</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/integrations/apprise_description.html
{% load humanize %}
{{ check.name_then_code }} is {{ status|upper }}.
{% if status == "down" and ping %}
Last ping was {{ ping.created|naturaltime }}.
{% endif %}

templates/integrations/group_form.html
{% extends "base_project.html" %}
{% load humanize static hc_extras %}

{% block title %}Group Integration for {{ site_name }}{% endblock %}


{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Group</h1>
        <p>Dispatch a notification to multiple integrations at once.</p>

        <h2>Integration Settings</h2>

        <form method="post" class="form-horizontal">
            {% csrf_token %}

            <div class="form-group {{ form.label.css_classes }}">
                <label for="id_label" class="col-sm-2 control-label">Label</label>
                <div class="col-sm-6">
                    <input
                        id="id_label"
                        type="text"
                        class="form-control"
                        name="label"
                        placeholder="VIP group"
                        value="{{ form.label.value|default:"" }}">

                    {% if form.label.errors %}
                    <div class="help-block">
                        {{ form.label.errors|join:"" }}
                    </div>
                    {% else %}
                    <span class="help-block">
                        Optional. If you add multiple groups,
                        the labels will help you tell them apart.
                    </span>
                    {% endif %}
                </div>
            </div>
            <div class="form-group {{ form.channels.css_classes }}">
                <label for="channels" class="col-sm-2 control-label">Integrations</label>
                <div id="channel-choices" class="col-sm-6">
                    {% for code, ch in form.channels.field.choices %}
                    <label class="checkbox-container">
                        <input
                            type="checkbox"
                            name="channels"
                            value="{{ code }}"
                            {% if code in form.channels.value %}checked{% endif %}>
                        <span class="checkmark"></span>

                        <img src="{% static ch.icon_path %}" alt="{{ ch.get_kind_display }}" class="kind-{{ ch.kind }}" />
                        <div class="name-desc">
                            {% if ch.name %}
                            {{ ch.name }}
                            {% else %}
                            <div class="unnamed">unnamed</div>
                            {% endif %}
                            <div class="channel-details-mini">
                            {% include "front/channel_description.html" with ch=ch %}
                            </div>
                        </div>
                    </label>
                    {% endfor %}
                    {% if form.channels.errors %}
                    <div class="help-block">
                        {{ form.channels.errors|join:"" }}
                    </div>
                    {% endif %}
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Save Group</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/integrations/matrix_description.html
{% load humanize %}
{% if status == "down" %}
    {{ check.name_then_code }} is DOWN.{% if ping %} Last ping was {{ ping.created|naturaltime }}.{% endif %}
{% else %}
    {{ check.name_then_code }} is now UP.
{% endif %}

templates/integrations/pagertree_description.html
{% load humanize %}
{{ check.name_then_code }} is {{ status|upper }}.
{% if status == "down" and ping %}
Last ping was {{ ping.created|naturaltime }}.
{% endif %}

templates/integrations/pagertree_title.html
{{ check.name_then_code|safe }} is {{ status|upper }}

templates/integrations/pd_description.html
{% if status == "down" %}
    {{ check.name_then_code|safe }} is DOWN
{% else %}
    {{ check.name_then_code|safe }} received a ping and is now UP
{% endif %}

templates/integrations/pushbullet_message.html
{% load humanize %}

{% if status == "down" %}
The check "{{ check.name_then_code|safe }}" is DOWN.{% if ping %} Last ping was {{ ping.created|naturaltime }}.{% endif %}
{% else %}
The check "{{ check.name_then_code|safe }}" received a ping and is now UP.
{% endif %}